- id: '1588587120496'
  alias: 'Living: edissons: motion — turn on'
  description: ''
  trigger:
  - entity_id: binary_sensor.living_motion
    platform: state
    to: 'on'
  condition:
  - after: sunset
    after_offset: -02:00:00
    condition: sun
  action:
  - data: {}
    entity_id: light.living_edisson_light
    service: light.turn_on
- id: '1588587120497'
  alias: 'Living: Turn off lights when no motion in a while'
  trigger:
  - entity_id: binary_sensor.living_motion
    for: 0:20:00
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.living_edisson_light
    service: light.turn_off
  - data: {}
    entity_id: light.living_main_light
    service: light.turn_off
- id: '1588607571701'
  alias: 'Living: Turn on main light when sunset and motion detected'
  description: ''
  trigger:
  - entity_id: binary_sensor.living_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - after: sunset
      condition: sun
    - before: sunset
      before_offset: +04:00:00
      condition: sun
  action:
  - data: {}
    entity_id: light.living_main_light
    service: light.turn_on
- id: '1589029647840'
  alias: say hello when mxtnr came back
  description: ''
  trigger:
  - entity_id: device_tracker.inv_phone
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - service: shell_command.say_alex_hello
- id: '1589219867446'
  alias: 'Hall: Turn on led stripe at 8:40 '
  description: ''
  trigger:
  - at: '8:40'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.hall_led_2
    service: switch.turn_on
- id: '1589220053566'
  alias: '*: night came'
  description: ''
  trigger:
  - event: sunset
    offset: +03:30:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: switch.hall_led_2
    service: switch.turn_off
  - data: {}
    entity_id: switch.hall_wall_light_2
    service: switch.turn_off
  - data: {}
    entity_id: light.living_edisson_light
    service: light.turn_off
  - data:
      speed: Auto
    entity_id: fan.xiaomi_air_purifier_2s
    service: fan.set_speed
- id: '1589296416725'
  alias: 'Hall: wall switch — light'
  description: ''
  trigger:
  - entity_id: binary_sensor.hall_wall_switch_2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: switch.hall_wall_light_2
    service: switch.toggle
- id: '1589296617107'
  alias: 'Hall: turn off wall light after 40 min'
  description: ''
  trigger:
  - entity_id: switch.hall_wall_light_2
    for: 00:40:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.hall_wall_light_2
    service: switch.turn_off
- id: '1589315913411'
  alias: '^: Enable automations'
  description: ''
  trigger:
  - at: 04:00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: automation.new_automation
    service: automation.turn_on
- id: '1589380016803'
  alias: 'Living: switch—edissons'
  description: ''
  trigger:
  - device_id: 09e58166923343f5bc376ebc11ce7393
    discovery_id: 0x00158d00039a2f89 click_single
    domain: mqtt
    platform: device
    subtype: single
    type: click
  condition: []
  action:
  - data: {}
    entity_id: light.living_edisson_light
    service: light.toggle
- id: '1589722525059'
  alias: 'HA: Load plants on restart'
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data: {}
    service: shell_command.update_plants
