homeassistant:
  customize: !include customize.yaml

  packages:
    air_purifier:  !include xiaomi_purifier1.yaml
    #air_purifier3: !include xiaomi_purifier3.yaml
    zigbee_graph: !include zigbee_graph.yaml
    #living_light: !include living_light.yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#   base_url: example.duckdns.org:8123
  ssl_certificate: .ssl/fullchain.pem
  ssl_key: .ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
    language: 'en'
    time_memory: 300
    service_name: google_say
    base_url: https://invntrm.ru:8812
    
frontend:
  themes:       !include_dir_merge_named themes

api:

group:          !include groups.yaml
automation:     !include automations.yaml
script:         !include scripts.yaml
scene:          !include scenes.yaml
plant:          !include plants.yaml
device_tracker: !include device_trackers.yaml # Detect who is at home
homekit:        !include homekit.yaml
history:        !include history_frontend.yaml
light:          !include lights.yaml
mqtt:           !include mqtt.yaml # Communicate through mosquitto with zigbee2mqtt, etc.
sensor:         !include sensors.yaml

binary_sensor:
  - platform: rpi_gpio
    ports:
      17: living_motion
  - platform: rpi_gpio
    invert_logic: true
    ports:
      26: living_tv_near_desk

switch:
  - platform: rpi_gpio
    ports:
      21: living_speakers

notify:
  - name: all
    platform: group
    services:
      - service: mobile_app_mxtnr # iphone
      - service: mobile_app_sveta # xiaomi
      - service: mobile_app_mextners_ipad_pro
      - service: mobile_app_n_msk_macfjxn # mxtnr mbp


camera:
#   platform: generic
#   stream_source: rtsp://192.168.1.18:554/1/h264major
#   username: admin
#   password: groveAdmin
#   verify_ssl: false
    platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.1.18:554/1/h264major



media_player:
  - platform: mpd
    name: volumio_mpd
    host: volumio.local

# squeezebox aka LMS оказался глючным говном, хотя в первый день шикарно работал
# на второй день половина колонок отваливалась с резкими неприятными звуками
#  - platform: squeezebox
#    host: rpi4.local

#  - platform: mpd
#    host: rpi4.local # localhost

#   - platform: samsungtv_custom
#     host: 192.168.88.242
#     port: 8001
#     mac: fc:03:9f:2c:b1:ec
#     name: SamsungTV
#     protocol: ctl_qled

# Возникла какая-то ошибка, а сначала перестали раьботать каналы, и никогда не обновлялся статус
# но это была первая хоть как-то заработавшая
#   - platform: samsungtv_qled
#     host: 192.168.1.74
#     # port: 8002
#     mac: fc:03:9f:2c:b1:ec
#     name: Samsung TV
#     update_method: 'smartthings'
#     app_list: '{"Netflix": "11101200001", "Youtube": "111299001912", "Apple TV": "3201807016597", "Plex": "3201512006963", "Prime Video": "3201512006785"}'
#     api_key: 'f49d6a37-3f21-43fc-94b7-2f222f0834fe'
#     device_id: 'b5dbc981-9410-48b9-87fb-51770581a111'


      
# # Выключать весь свет когда все ушли и на оборот
# device_sun_light_trigger:
#   device_group: group.home_persons

# так нельзя похоже :()
# fan:
#     - platform: switch
#       name: wc_fan
#       entity_id: switch.wc_fan

#shell_command:
  #say_alex_hello: 'echo "Привет, Саша! С дал+го+ждан+ным ваз+ращением" | /usr/bin/festival --language russian --tts'
  #say_sec: play --volume .5 /home/pi/one-sec.mp3  #'amixer cset numid=1 -- -500; mpg321 /home/pi/one-sec.mp3; amixer cset numid=1 -- 300'
  #update_plants: "ssh orpik2.local 'sudo systemctl restart miflora.service'"
  

cover:
  platform: mqtt
  name: "Living Window Vent"
  unique_id: "drivent-7c6"
  device:
    identifiers: "drivent-7c6"
    manufacturer: "Drivent"
    model: "v1"
    name: "drivent-7c6"
    sw_version: "1.5.3"
  command_topic: "drivent-7c6/setTargetPosition"
  position_topic: "drivent-7c6/CurrentPosition"
  set_position_topic: "drivent-7c6/setTargetPosition"
  payload_open: "100"
  payload_close: "0"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  availability:
    - "topic": "drivent-7c6/LWT"
      payload_available: "1"
      payload_not_available: "0"


rest_command:
  upd_cld:
    url: "http://localhost:8080/roscha/api/wc/water"
    method: "put"
    payload: '{"cld": {{states("input_number.water_cold")}}, "upd": "{{now().isoformat()}}" }'
    content_type: "application/json;charset=utf-8"
  upd_hot:
    url: "http://localhost:8080/roscha/api/wc/water"
    method: "put"
    payload: '{"hot": {{states("input_number.water_hot")}}, "upd": "{{now().isoformat()}}"}'
    content_type: "application/json;charset=utf-8"






