homeassistant:
  customize: !include customize.yaml

  packages:
    air_purifier: !include xiaomi_purifier.yaml
    zigbee_graph: !include zigbee_graph.yaml
    #living_light: !include living_light.yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

# switch: !include switches.yaml
group:          !include groups.yaml
automation:     !include automations.yaml
script:         !include scripts.yaml
scene:          !include scenes.yaml
plant:          !include plants.yaml
device_tracker: !include device_trackers.yaml # Detect who is at home
homekit: # Send HomeAssistant devices into Homekit
    filter:
        exclude_domains:
            - device_tracker
            - media_player
            - person
        exclude_entity_globs:
            - '*._*'
            - '*.transmission*'
        exclude_entities:
            - switch.kitchen_main_light_2
            - binary_sensor.updater
            - sensor.hacs
            - switch.living_edisson_light_switch
            - binary_sensor.button
            - switch.kitchen_main_light
            - switch.hall_wall_light
            - binary_sensor.hall_wall_switch
            - switch.hall_led_2
            - switch.hall_wall_light_2
            - switch.living_edisson_light
            - switch.kitchen_main_light_2

history:        !include history_frontend.yaml
light:          !include lights.yaml
mqtt:           !include mqtt.yaml # Communicate through mosquitto with zigbee2mqtt, etc.

media_player:
#  - platform: mpd
#    host: rpi4.local # localhost
  - platform: squeezebox
    host: rpi4.local
#   - platform: samsungtv_custom
#     host: 192.168.88.242
#     port: 8001
#     mac: fc:03:9f:2c:b1:ec
#     name: SamsungTV
#     protocol: ctl_qled

  - platform: samsungtv_qled
    host: 192.168.1.74
    # port: 8002
    mac: fc:03:9f:2c:b1:ec
    name: Samsung TV
    update_method: 'smartthings'
    app_list: '{"Netflix": "11101200001", "Youtube": "111299001912", "Apple TV": "3201807016597", "Plex": "3201512006963", "Prime Video": "3201512006785"}'
    api_key: 'f49d6a37-3f21-43fc-94b7-2f222f0834fe'
    device_id: 'b5dbc981-9410-48b9-87fb-51770581a111'


binary_sensor:
  - platform: rpi_gpio
    ports:
      17: living_motion

  - platform: template
    sensors:
      entry_door_motion_final:
        friendly_name: EntryDoor Motion

        value_template: >- 
          {%- if is_state("input_boolean.entry_door_motion", "on") -%}
            true
          {%- else -%}
            false
          {%- endif -%} 

        icon_template: >
          {% if is_state("input_boolean.entry_door_motion", "on") %}
            mdi:walk
          {% else %}
            mdi:run
          {% endif %}
        #
        #  {% if is_state("input_boolean.entry_door_motion", "on") %} 
        #    rgb(251, 210, 41)
        #  {% else %}
        #    'rgb(54, 95, 140)'
        #  {% endif %}

# # Выключать весь свет когда все ушли и на оборот
# device_sun_light_trigger:
#   device_group: group.home_persons



#shell_command:
  #say_alex_hello: 'echo "Привет, Саша! С дал+го+ждан+ным ваз+ращением" | /usr/bin/festival --language russian --tts'
  #say_sec: play --volume .5 /home/pi/one-sec.mp3  #'amixer cset numid=1 -- -500; mpg321 /home/pi/one-sec.mp3; amixer cset numid=1 -- 300'
  #update_plants: "ssh orpik2.local 'sudo systemctl restart miflora.service'"
  
