- platform: switch
  name: Living Main
  entity_id: switch.0x847127fffea207cd_switch # living main light button
- platform: switch
  name: Bedroom Main
  entity_id: switch.0x847127fffea205d5_switch # bedroom main light button

- platform: mqtt
  name: bedroom_light
  state_topic: 'bedroom/light/switch_state'
  payload_on: "ON"
  payload_off: "OFF"
  command_topic: 'bedroom/light/switch'
  brightness_state_topic: "bedroom/light/state"
  brightness_command_topic: 'bedroom/light/dimm'
  brightness_scale: 2
  qos: 1
  retain: true
  optimistic: false

## Виртуальные диммеры. Переключение уровней света
#   - platform: template
#     lights:
#       hallway_lights:
#         friendly_name: "Hallway Lights"
#         level_template: "{{ state_attr('sensor.theater_brightness', 'lux')|int }}"
#         value_template: "{{ state_attr('sensor.theater_brightness', 'lux')|int > 0 }}"
#         turn_on:
#           service: script.theater_lights_on
#         turn_off:
#           service: script.theater_lights_off
#         set_level:
#           service: script.theater_lights_level
#           data:
#             brightness: "{{ brightness }}"
