# Xiaomi purifier 2s

fan:
  - platform: xiaomi_miio
    model: zhimi.airpurifier.ma2
    host: '192.168.1.71'
    token: 'b2e3903e0ee64e12a45ce082d5053ac4'
    name: "Xiaomi Air Purifier 2S"

  
sensor:
  # Xiaomi Air Purifier 2S
  - platform: template
    sensors:
      xiaomi_airpurifier_temp:
        friendly_name: "Temperature"
        value_template: "{{ state_attr('fan.xiaomi_air_purifier_2s', 'temperature') }}"
        unit_of_measurement: "°C"
        device_class: "temperature"
      xiaomi_airpurifier_humidity:
        friendly_name: "Humidity"
        value_template: "{{ state_attr('fan.xiaomi_air_purifier_2s', 'humidity') }}"
        unit_of_measurement: "%"
        device_class: "humidity"
      xiaomi_airpurifier_air_quality_pm25:
        friendly_name: "Air quality"
        value_template: "{{ state_attr('fan.xiaomi_air_purifier_2s', 'aqi') }}"
        unit_of_measurement: "μg/m³"
        icon_template: "mdi:weather-fog"
      xiaomi_airpurifier_speed:
        friendly_name: "Fan speed"
        value_template: "{{ state_attr('fan.xiaomi_air_purifier_2s', 'motor_speed') }}"
        unit_of_measurement: "rpm"
        icon_template: "mdi:speedometer"
      xiaomi_airpurifier_mode:
        friendly_name: "Mode"
        value_template: "{{ state_attr('fan.xiaomi_air_purifier_2s', 'speed') }}"
        icon_template: "mdi:speedometer"
      xiaomi_airpurifier_filter_remaining:
        friendly_name: "Filter remaining"
        value_template: "{{ state_attr('fan.xiaomi_air_purifier_2s', 'filter_life_remaining') }}"
        unit_of_measurement: "%"
        icon_template: "mdi:heart-outline"

switch:
  # Xiaomi Air Purifier 2S
  - platform: template
    switches:
      xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_2s', 'led', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_led_on
          data:
            entity_id: fan.xiaomi_air_purifier_2s
        turn_off:
          service: xiaomi_miio.fan_set_led_off
          data:
            entity_id: fan.xiaomi_air_purifier_2s
        icon_template: "mdi:lightbulb-outline"
      xiaomi_airpurifier_child_lock:
        friendly_name: "Child lock"
        value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_2s', 'child_lock', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_child_lock_on
          data:
            entity_id: fan.xiaomi_air_purifier_2s
        turn_off:
          service: xiaomi_miio.fan_set_child_lock_off
          data:
            entity_id: fan.xiaomi_air_purifier_2s
        icon_template: "mdi:lock-outline"
      xiaomi_airpurifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_2s', 'buzzer', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_buzzer_on
          data:
            entity_id: fan.xiaomi_air_purifier_2s
        turn_off:
          service: xiaomi_miio.fan_set_buzzer_off
          data:
            entity_id: fan.xiaomi_air_purifier_2s
        icon_template: "mdi:volume-high"
  
input_select:
  # Xiaomi Air Purifier 2S
  xiaomi_airpurifier_mode:
    name: Mode
    options:
      - Auto
      - Silent
      - Favorite
    icon: "mdi:animation-outline"

input_number:
  # Xiaomi Air Purifier 2S
  xiaomi_airpurifier_favorite_level:
    name: "Favorite level"
    initial: 0
    min: 0
    max: 14
    step: 1
    icon: "mdi:weather-windy"
    


automation:
  # manual control
  - alias: Air Purifier mode change
    trigger:
      entity_id: input_select.xiaomi_airpurifier_mode
      platform: state
    action:
      service: fan.set_speed
      data_template:
        entity_id: fan.xiaomi_air_purifier_2s
        speed: '{{ states.input_select.xiaomi_airpurifier_mode.state }}'
  - alias: Air Purifier favorite level change
    trigger:
      entity_id: input_number.xiaomi_airpurifier_favorite_level
      platform: state
    action:
      service: xiaomi_miio.fan_set_favorite_level
      data_template:
        entity_id: fan.xiaomi_air_purifier_2s
        level: '{{ states.input_number.xiaomi_airpurifier_favorite_level.state | int }}'


  # control feedback
  - alias: Air Purifier mode changed
    trigger:
      platform: template
      # entity_id: fan.xiaomi_air_purifier_2s
      value_template: "{{ states.fan.xiaomi_air_purifier_2s.attributes.speed }}"
    action:
      service: input_select.select_option
      entity_id: input_select.xiaomi_airpurifier_mode
      data_template:
        option: '{{ states.fan.xiaomi_air_purifier_2s.attributes.speed }}'
  - alias: Air Purifier favorite level changed
    trigger:
      platform: template
      # entity_id: fan.xiaomi_air_purifier_2s
      value_template: "{{ states.fan.xiaomi_air_purifier_2s.attributes.favorite_level }}"
    action:
      service: input_number.set_value
      entity_id: input_number.xiaomi_airpurifier_favorite_level
      data_template:
        value: '{{ states.fan.xiaomi_air_purifier_2s.attributes.favorite_level }}'

    # real automations
  - id: '1590777599769'
    alias: 'Purifier: dirty 3 '
    description: 'Minimal level '
    trigger:
    - above: '2'
      below: '8'
      entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
      for: 00:00:12
      platform: numeric_state
    condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    action:
    - data:
        level: 4
      entity_id: fan.xiaomi_air_purifier_2s
      service: xiaomi_miio.fan_set_favorite_level
    - data:
        speed: Favorite
      entity_id: fan.xiaomi_air_purifier_2s
      service: fan.set_speed
    - data:
        value: 4
      entity_id: input_number.xiaomi_airpurifier_favorite_level
      service: input_number.set_value
    - data:
        option: Favorite
      entity_id: input_select.xiaomi_airpurifier_mode
      service: input_select.select_option

  - id: '1590778322846'
    alias: 'Purifier: dirty 8'
    description: 'middle level'
    trigger:
    - above: '7'
      below: '16'
      entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
      for: 00:00:10
      platform: numeric_state
    condition: 
    - condition: or
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    action:
    - data:
        level: 8
      entity_id: fan.xiaomi_air_purifier_2s
      service: xiaomi_miio.fan_set_favorite_level
    - data:
        speed: Favorite
      entity_id: fan.xiaomi_air_purifier_2s
      service: fan.set_speed
    - data:
        value: 8
      entity_id: input_number.xiaomi_airpurifier_favorite_level
      service: input_number.set_value
    - data:
        option: Favorite
      entity_id: input_select.xiaomi_airpurifier_mode
      service: input_select.select_option

  - id: '1590778322816'
    alias: 'Purifier: dirty 16'
    description: 'max level'
    trigger:
    - above: '15'
      entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
      for: 00:00:10
      platform: numeric_state
    condition: 
    - condition: or
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    action:
    - data:
        level: 16
      entity_id: fan.xiaomi_air_purifier_2s
      service: xiaomi_miio.fan_set_favorite_level
    - data:
        value: 16
      entity_id: input_number.xiaomi_airpurifier_favorite_level
      service: input_number.set_value
    - data:
        speed: Favorite
      entity_id: fan.xiaomi_air_purifier_2s
      service: fan.set_speed
    - data:
        option: Favorite
      entity_id: input_select.xiaomi_airpurifier_mode
      service: input_select.select_option

  - id: '1590779035335'
    alias: 'Purifier: idle'
    description: 'silent'
    trigger:
    - below: '2'
      entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
      for: 00:01:00
      platform: numeric_state
    condition:
      - condition: state
        entity_id: sensor.xiaomi_airpurifier_mode
        state: Favorite
        
    action:
    - data:
        speed: Favorite
      entity_id: fan.xiaomi_air_purifier_2s
      service: fan.set_speed
    - data:
        option: Favorite
      entity_id: input_select.xiaomi_airpurifier_mode
      service: input_select.select_option
    - data:
        level: 1
      entity_id: fan.xiaomi_air_purifier_2s
      service: xiaomi_miio.fan_set_favorite_level
    - data:
        value: 1
      entity_id: input_number.xiaomi_airpurifier_favorite_level
      service: input_number.set_value


group:
  airpurifier:
    name: Air Purifier group
    entities:
      - fan.xiaomi_miio_device
      - input_select.xiaomi_airpurifier_mode
      - input_number.xiaomi_airpurifier_favorite_level
#      - input_number.xiaomi_airpurifier_volume # AirPurifier Pro
      - switch.xiaomi_airpurifier_child_lock
      - switch.xiaomi_airpurifier_led
      - switch.xiaomi_airpurifier_buzzer
      - sensor.xiaomi_airpurifier_speed
      - sensor.xiaomi_airpurifier_filter_remaining
      - sensor.xiaomi_airpurifier_air_quality_pm25
      - sensor.xiaomi_airpurifier_temp
      - sensor.xiaomi_airpurifier_humidity
