esphome:
  name: esp_kitchen_sink
  platform: ESP8266
  board: d1_mini

wifi:
  ssid:     !secret wifi_ssid
  password: !secret wifi_pswd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Kitchen Sink"
    password: "FE06Pm5wTTIL"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#
# Switch buttons input pins
binary_sensor:
  - platform: gpio
    name: kitchen_sink_motion
    pin:
      number: D4
      mode: INPUT_PULLUP
    filters: # debounce
      - delayed_on: 50ms
      - delayed_off: 50ms
#
# Relays
output:
  - platform: gpio # esp8266_pwm
    id: kitchen_sink_relay
    pin: D3
    inverted: False

#
# Frontend to relays
light:
  - platform: binary # monochromatic
    name: kitchen_sink
    output: kitchen_sink_relay
